from PyQt5 import QtCore, QtGui, QtWidgets
import platform
import os


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 580)
        MainWindow.setMinimumSize(QtCore.QSize(801, 580))
        MainWindow.setMaximumSize(QtCore.QSize(801, 580))
        MainWindow.setWindowIcon(QtGui.QIcon('resources/img/MultiMate.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timeline = QtWidgets.QSlider(self.centralwidget)
        self.timeline.setGeometry(QtCore.QRect(10, 490, 781, 22))
        self.timeline.setPageStep(1)
        self.timeline.setOrientation(QtCore.Qt.Horizontal)
        self.timeline.setObjectName("timeline")
        self.timeline.setMaximum(1000)

        self.playpausebutton = QtWidgets.QPushButton(self.centralwidget)
        self.playpausebutton.setEnabled(True)
        self.playpausebutton.setGeometry(QtCore.QRect(390, 520, 40, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.playpausebutton.setFont(font)
        self.playpausebutton.setStyleSheet("background-color: rgba(10, 0, 0, 0);\n"
                                           "")
        self.playpausebutton.setText("")
        self.playpausebutton.setObjectName("playpausebutton")
        self.playpausePicture = QtWidgets.QLabel(self.centralwidget)
        self.playpausePicture.setGeometry(QtCore.QRect(390, 520, 40, 40))
        self.playpausePicture.setText("")
        self.playpausePicture.setPixmap(QtGui.QPixmap("resources/img/MultiMate40x40.png"))
        self.playpausePicture.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.playpausePicture.setObjectName("playpausePicture")

        self.prevbutton = QtWidgets.QPushButton(self.centralwidget)
        self.prevbutton.setEnabled(True)
        self.prevbutton.setGeometry(QtCore.QRect(340, 520, 40, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.prevbutton.setFont(font)
        self.prevbutton.setStyleSheet("background-color: rgba(10, 0, 0, 0);\n"
                                      "")
        self.prevbutton.setText("")
        self.prevbutton.setObjectName("prevbutton")
        self.prevPicture = QtWidgets.QLabel(self.centralwidget)
        self.prevPicture.setGeometry(QtCore.QRect(340, 520, 40, 40))
        self.prevPicture.setText("")
        self.prevPicture.setPixmap(QtGui.QPixmap("resources/img/prev.png"))
        self.prevPicture.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.prevPicture.setObjectName("prevPicture")
        self.nextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.nextbutton.setEnabled(True)
        self.nextbutton.setGeometry(QtCore.QRect(440, 520, 40, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        self.nextbutton.setFont(font)
        self.nextbutton.setStyleSheet("background-color: rgba(10, 0, 0, 0);\n"
                                      "")
        self.nextbutton.setText("")
        self.nextbutton.setObjectName("nextbutton")
        self.nextPicture = QtWidgets.QLabel(self.centralwidget)
        self.nextPicture.setGeometry(QtCore.QRect(440, 520, 40, 40))
        self.nextPicture.setText("")
        self.nextPicture.setPixmap(QtGui.QPixmap("resources/img/next.png"))
        self.nextPicture.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.nextPicture.setObjectName("nextPicture")

        self.speedBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speedBox.setGeometry(QtCore.QRect(10, 515, 62, 22))
        self.speedBox.setDecimals(1)
        self.speedBox.setProperty("value", 1.0)
        self.speedBox.setSingleStep(0.2)
        self.speedBox.setObjectName("speedBox")
        self.timenow = QtWidgets.QTextEdit(self.centralwidget)
        self.timenow.setGeometry(QtCore.QRect(713, 515, 81, 23))
        self.timenow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.timenow.setObjectName("timenow")
        self.speedTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.speedTextLabel.setGeometry(QtCore.QRect(25, 536, 47, 13))
        self.speedTextLabel.setObjectName("speedTextLabel")
        self.timeTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeTextLabel.setGeometry(QtCore.QRect(740, 536, 47, 13))
        self.timeTextLabel.setObjectName("timeTextLabel")
        self.volumeDial = QtWidgets.QDial(self.centralwidget)
        self.volumeDial.setGeometry(QtCore.QRect(719, 0, 81, 81))
        self.volumeDial.setStyleSheet("")
        self.volumeDial.setMinimum(1)
        self.volumeDial.setMaximum(100)
        self.volumeDial.setPageStep(1)
        self.volumeDial.setProperty("value", 100)
        self.volumeDial.setObjectName("volumeDial")
        self.VolDialBG = QtWidgets.QLabel(self.centralwidget)
        self.VolDialBG.setGeometry(QtCore.QRect(720, 0, 81, 81))
        self.VolDialBG.setText("")
        self.VolDialBG.setPixmap(QtGui.QPixmap("resources/img/MultiMate80x80.png"))
        self.VolDialBG.setObjectName("VolDialBG")
        self.playlistsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.playlistsComboBox.setGeometry(QtCore.QRect(0, 0, 231, 22))
        self.playlistsComboBox.setCurrentText("")
        self.playlistsComboBox.setDuplicatesEnabled(True)
        self.playlistsComboBox.setObjectName("playlistsComboBox")
        for playlist in os.listdir(os.getcwd()):
            self.playlistsComboBox.addItem(playlist)
        self.nowPlaying = QtWidgets.QTextBrowser(self.centralwidget)
        self.nowPlaying.setGeometry(QtCore.QRect(10, 460, 781, 23))
        self.nowPlaying.setObjectName("nowPlaying")
        self.openPlaylistButton = QtWidgets.QPushButton(self.centralwidget)
        self.openPlaylistButton.setGeometry(QtCore.QRect(230, 0, 75, 23))
        self.openPlaylistButton.setObjectName("openPlaylistButton")

        self.songList = QtWidgets.QListWidget(self.centralwidget)
        self.songList.setGeometry(QtCore.QRect(0, 43, 301, 411))
        self.songList.setObjectName("songList")

        self.TextAllSongs = QtWidgets.QTextEdit(self.centralwidget)
        self.TextAllSongs.setGeometry(QtCore.QRect(0, 20, 301, 23))
        self.TextAllSongs.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.TextAllSongs.setObjectName("TextAllSongs")
        self.toFindName = QtWidgets.QTextEdit(self.centralwidget)
        self.toFindName.setGeometry(QtCore.QRect(310, 0, 331, 23))
        self.toFindName.setObjectName("toFindName")
        self.findSongButton = QtWidgets.QPushButton(self.centralwidget)
        self.findSongButton.setGeometry(QtCore.QRect(640, 0, 75, 23))
        self.findSongButton.setObjectName("findSongButton")
        self.foundSongs = QtWidgets.QComboBox(self.centralwidget)
        self.foundSongs.setGeometry(QtCore.QRect(310, 30, 331, 22))
        self.foundSongs.setObjectName("foundSongs")
        self.addThisSongButton = QtWidgets.QPushButton(self.centralwidget)
        self.addThisSongButton.setGeometry(QtCore.QRect(640, 30, 75, 23))
        self.addThisSongButton.setObjectName("addThisSongButton")
        self.mixButton = QtWidgets.QPushButton(self.centralwidget)
        self.mixButton.setGeometry(QtCore.QRect(720, 90, 75, 41))
        self.mixButton.setObjectName("mixButton")

        self.playlistSettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.playlistSettingsButton.setGeometry(QtCore.QRect(720, 140, 75, 51))
        self.playlistSettingsButton.setObjectName("playlistSettingsButton")

        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(720, 200, 75, 45))
        self.settingsButton.setObjectName("settingsButton")

        self.extendedFunctButton = QtWidgets.QPushButton(self.centralwidget)
        self.extendedFunctButton.setGeometry(QtCore.QRect(720, 260, 75, 45))
        self.extendedFunctButton.setObjectName("extendedFunctButton")

        if platform.system() == "Darwin":  # for MacOS
            self.videoframe = QtWidgets.QMacCocoaViewContainer(self.centralwidget)
        else:
            self.videoframe = QtWidgets.QFrame(self.centralwidget)
        self.videoframe.setGeometry(QtCore.QRect(310, 60, 394, 394))
        self.videoframe.setObjectName("videoframe")
        self.timeline.raise_()
        self.playpausePicture.raise_()
        self.prevPicture.raise_()
        self.nextPicture.raise_()
        self.speedBox.raise_()
        self.nextbutton.raise_()
        self.prevbutton.raise_()
        self.playpausebutton.raise_()
        self.timenow.raise_()
        self.speedTextLabel.raise_()
        self.timeTextLabel.raise_()
        self.VolDialBG.raise_()
        self.volumeDial.raise_()
        self.playlistsComboBox.raise_()
        self.nowPlaying.raise_()
        self.openPlaylistButton.raise_()
        self.songList.raise_()
        self.TextAllSongs.raise_()
        self.toFindName.raise_()
        self.findSongButton.raise_()
        self.foundSongs.raise_()
        self.addThisSongButton.raise_()
        self.mixButton.raise_()
        self.playlistSettingsButton.raise_()
        self.videoframe.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.timer = QtCore.QTimer(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MultiMate Player"))
        self.speedBox.setPrefix(_translate("MainWindow", "x"))
        self.speedTextLabel.setText(_translate("MainWindow", "Speed"))
        self.timeTextLabel.setText(_translate("MainWindow", "Time"))
        self.nowPlaying.setPlaceholderText(_translate("MainWindow", "Choose playlist and open it..."))
        self.openPlaylistButton.setText(_translate("MainWindow", "Open playlist"))
        self.TextAllSongs.setHtml(_translate("MainWindow",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                             "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Songs in playlist</p></body></html>"))
        self.findSongButton.setText(_translate("MainWindow", "Find song"))
        self.addThisSongButton.setText(_translate("MainWindow", "Add this song"))
        self.mixButton.setText(_translate("MainWindow", "Mix"))
        self.playlistSettingsButton.setText(_translate("MainWindow", "Playlist \nsettings"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.extendedFunctButton.setText(_translate("MainWindow", "Extended \n functions"))
